version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  reviewers:
  - QAutomatron
  assignees:
  - QAutomatron
  ignore:
  - dependency-name: org.jetbrains.kotlin:kotlin-reflect
    versions:
    - 1.4.21-2
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk8
    versions:
    - 1.4.21-2
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.21-2
  - dependency-name: io.github.microutils:kotlin-logging
    versions:
    - 2.0.4
  - dependency-name: io.appium:java-client
    versions:
    - 7.4.1
  - dependency-name: com.willowtreeapps.assertk:assertk
    versions:
    - "0.23"
  - dependency-name: org.testng:testng
    versions:
    - 7.3.0
